AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An example AWS SAM template for a Python Lambda function.
Resources:
  VelourScraper:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: velour-scraper
      Handler: velour_scraper.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Description: A scraper of the velour website that runs on a cron job.
      Role: arn:aws:iam::868253984511:role/velour-scraper-role
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonS3FullAccess
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-s6yfaclh8opc/1c0b390d6f5c143d9d31db15a13fe331
      Environment: null
    Metadata:
      SamResourceId: VelourScraper
Outputs:
  VelourScraper:
    Description: Velour Scraper Function ARN
    Value:
      Fn::GetAtt:
      - VelourScraper
      - Arn
  VelourScraperIamRole:
    Description: Implicit IAM Role created for Velour Scraper
    Value:
      Fn::GetAtt:
      - VelourScraperRole
      - Arn
