AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An example AWS SAM template for a Python Lambda function.

Globals:
  Function:
    Timeout: 120
    MemorySize: 128

Parameters:
  OpenAIAPIKey:
    Type: String
    Default: ""
  SpotifyClientID:
    Type: String
    Default: ""
  SpotifyClientSecret:
    Type: String
    Default: ""
  
Resources:
  VelourScraper:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: velour-scraper
      Handler: velour_scraper.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Role: arn:aws:iam::868253984511:role/velour-scraper-role
      Environment:
        Variables:
          OpenAIAPIKey: !Ref OpenAIAPIKey
          SpotifyClientID: !Ref SpotifyClientID
          SpotifyClientSecret: !Ref SpotifyClientSecret

Outputs:
  VelourScraper:
    Description: "Velour Scraper Function ARN"
    Value: !GetAtt VelourScraper.Arn